### ISSUE TITLE
Schematic audio kit

### ISSUE THREAD

**Issue by Patsjemoe** [Ai-Thinker-Open/ESP32-A1S-AudioKit#17]
Hi,
Trying to find the schematic of the audio kit to check if the HW is same as lyrat-mini, so I can use the board I have. 

Where to find this?
Regards
Ludo

**Comment by stetro** [comment]
Hi, I'm currently using this. 
[esp32-audio-kit_v2.1-open_custom.pdf](https://github.com/Ai-Thinker-Open/ESP32-A1S-AudioKit/files/5972241/esp32-audio-kit_v2.1-open_custom.pdf)

**Comment by Patsjemoe** [comment]
Hi Stetro,
Thanks. 
Regards
Ludo
