### ISSUE TITLE
Unable to listen to audio using headphone in my brand new esp32 audio kit

### ISSUE THREAD

**Issue by jalakamkiranadspl** [Ai-Thinker-Open/ESP32-A1S-AudioKit#19]
Hello. I have flashed the play_mp3 example to my brand new esp32 audio kit and using an ear phone to check the sound. I am not able to hear anything from the board. Here are the logs.
entry 0x40080678
I (29) boot: ESP-IDF v4.4-dev-4-g73db14240 2nd stage bootloader
I (29) boot: compile time 11:08:38
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (49) boot.esp32: SPI Speed      : 40MHz
I (49) boot.esp32: SPI Mode       : DIO
I (49) boot.esp32: SPI Flash Size : 2MB
I (54) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (77) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (85) boot:  2 factory          factory app      00 00 00010000 00100000
I (92) boot: End of partition table
I (97) boot_comm: chip revision: 1, min. application chip revision: 0
I (104) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1f4cch (128204) map
I (157) esp_image: segment 1: paddr=0002f4f4 vaddr=3ffb0000 size=00b24h (  2852) load
I (159) esp_image: segment 2: paddr=00030020 vaddr=400d0020 size=2278ch (141196) map
I (213) esp_image: segment 3: paddr=000527b4 vaddr=3ffb0b24 size=01dd4h (  7636) load
I (216) esp_image: segment 4: paddr=00054590 vaddr=40080000 size=0c0b0h ( 49328) load
I (245) boot: Loaded app from partition at offset 0x10000
I (245) boot: Disabling RNG early entropy source...
I (257) cpu_start: Pro cpu up.
I (257) cpu_start: Starting app cpu, entry point is 0x40080ff4
0x40080ff4: call_start_cpu1 at /home/jalakamkiran/esp/esp-idf/components/esp_system/port/cpu_start.c:143

I (0) cpu_start: App cpu up.
I (271) cpu_start: Pro cpu start user code
I (271) cpu_start: cpu freq: 160000000
I (271) cpu_start: Application information:
I (276) cpu_start: Project name:     play_mp3
I (281) cpu_start: App version:      12c1833
I (286) cpu_start: Compile time:     Mar 24 2021 11:08:28
I (292) cpu_start: ELF file SHA256:  59adb7662e3732bd...
I (298) cpu_start: ESP-IDF:          v4.4-dev-4-g73db14240
I (304) heap_init: Initializing. RAM available for dynamic allocation:
I (311) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (317) heap_init: At 3FFB3278 len 0002CD88 (179 KiB): DRAM
I (324) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (330) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (336) heap_init: At 4008C0B0 len 00013F50 (79 KiB): IRAM
I (344) spi_flash: detected chip: winbond
I (347) spi_flash: flash io: dio
W (351) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (365) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (375) PLAY_MP3_FLASH: [ 1 ] Start audio codec chip
I (385) PLAY_MP3_FLASH: [ 2 ] Create audio pipeline, add all elements to pipeline, and subscribe pipeline event
I (395) PLAY_MP3_FLASH: [2.1] Create mp3 decoder to decode mp3 file and set custom read callback
I (405) PLAY_MP3_FLASH: [2.2] Create i2s stream to write data to codec chip
I (435) PLAY_MP3_FLASH: [2.3] Register all elements to audio pipeline
I (435) PLAY_MP3_FLASH: [2.4] Link it together [mp3_music_read_cb]-->mp3_decoder-->i2s_stream-->[codec_chip]
I (445) PLAY_MP3_FLASH: [ 3 ] Set up  event listener
I (445) PLAY_MP3_FLASH: [3.1] Listening event from all elements of pipeline
I (455) PLAY_MP3_FLASH: [ 4 ] Start audio_pipeline
I (475) PLAY_MP3_FLASH: [ * ] Receive music info from mp3 decoder, sample_rates=44100, bits=16, ch=2
I (7255) PLAY_MP3_FLASH: [ 5 ] Stop audio_pipeline
E (7255) AUDIO_ELEMENT: [mp3] Element already stopped
E (7255) AUDIO_ELEMENT: [i2s] Element already stopped
W (7265) AUDIO_PIPELINE: There are no listener registered
W (7265) AUDIO_ELEMENT: [i2s] Element has not create when AUDIO_ELEMENT_TERMINATE
W (7275) AUDIO_ELEMENT: [mp3] Element has not create when AUDIO_ELEMENT_TERMINATE

I am using ESP-IDF v4.4. I am very sure that my earphones are working. The esp32 audio kit is having its Green LED and red led on as shown in the picture.

![image](https://user-images.githubusercontent.com/73413933/112263064-ae2a7a80-8c94-11eb-9c05-398d0cbe72b2.png)
The image shows how I have connected the earphones and I have connected to the earphone jack. Please specify what is it that I am doing wrong. Thanks in advance. or is it a version issue?

**Comment by jalakamkiranadspl** [comment]
To who ever is facing this issue.Since no one from the AI thinker had responded I had to get the external repository from github. 
@chandrabezzo has created a repo for porting the esp adf for AI thinker board and ported some of the examples. I forked it from him and have made some deprecation changes. You can find the repo linked below.
[](https://github.com/jalakamkiranadspl/Ai-thinker-audio-kit)

**Comment by chandrabezzo** [comment]
Hi @jalakamkiranadspl thank you for your reporting. To appreciate me can you fork out of this repo and make changes? Not clone then publish in your repo.

**Comment by jalakamkiranadspl** [comment]
Hey Chandra bezzo...I will definitely do that.

**Comment by jalakamkiranadspl** [comment]
Also can you check my other email I have written to you regarding an issue
with Speech recognition ASR. Please help me out with that.
Thanks.
I am quite new to github. So I did what I thought was good (mentioning you
in comments) sorry about not forking your repo at first itself.

**Comment by jalakamkiranadspl** [comment]
@chandrabezzo  I have forked and done the same. Please check it out. :)
