### ISSUE TITLE
undefined reference to `AUDIO_CODEC_AC101_CODEC_HANDLE'

### ISSUE THREAD

**Issue by GabeHC** [Ai-Thinker-Open/ESP32-A1S-AudioKit#2]
How do I solve this? 

esp-idf/audio_board/libaudio_board.a(board.c.obj):(.literal.audio_board_codec_init+0x4): undefined reference to `AUDIO_CODEC_AC101_CODEC_HANDLE'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by GabeHC** [comment]
Fixed it by adding ac101 into CMakeLists.txt in audio_hal directory!

**Comment by stahlnow** [comment]
> Fixed it by adding ac101 into CMakeLists.txt in audio_hal directory!
thx, that helped me!
