### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by chandrabezzo** [Ai-Thinker-Open/ESP32-A1S-AudioKit#3]
I was create a new project of ESP32 using esp-idf using eclipse IDE, I try the example code using SD Card but I can't running any example that using SD Card. I got the error in initialized SD Card (mount SD Card). I used 16GB SD Card, is there a limit on the SD Card that can be used?

**Comment by schreibfaul1** [comment]
MISO GPIO2
MOSI GPIO15
SCK GPIO14
SD_CS GPIO13, Swich 1 off, 2 on, 3 on, 4 off, 5 off
https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/examples/ESP32-A1S/ESP32_A1S.ino
